### ISSUE TITLE
Logo improvement

### ISSUE THREAD

**Issue by frankfont** [bah-insignia/zcmd#1]
The current logo of a simple killer whale and abstract containers is just a placeholder.  Can someone come up with a better logo for ZCMD?

**Comment by richardbmx** [comment]
@frankfont  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by frankfont** [comment]
@richardbmx whats the best way for us to have a look at them?

**Comment by richardbmx** [comment]
@frankfont  Happy day, sorry for the delay I did not get any notification of your response ... I would like to present these two proposals, one based on your original logo but improved to give it more style and that is visually more attractive, and a second proposal made with a set of letters with the text ZCMD with a very minimalist style, I hope you like it if you want some change you just have to ask me and I will gladly do it, if you want one of the two designs I can send you all the necessary files for its use.

![logo136](https://user-images.githubusercontent.com/35604837/58999217-9db0c380-87d2-11e9-882f-b9986a087d32.png)

**Comment by cjdesautels** [comment]
My vote goes for the black and gray Orca. Opensource is great. Who would of thought we'd get a slick logo merely by asking.

@richardbmx: Thanks a bunch for this.

**Comment by frankfont** [comment]
@richardbmx , all these logos bring a different energy --- less boring than the existing logo currently at the https://github.com/bah-insignia/zcmd page.  The project is MIT open-sourced, so any logos included would be open and free for use in the same way.

Between all the logos proposed, I lean toward the same one @cjdesautels  mentioned.  Would it be possible to reflect the concept of "containers" in that logo in the same fun style of the orca and zcmd lettering?  The docker technology is about containerization (thus the crude attempt of the existing logo to show some boxes).

PS -- The official Docker logo is a whale with shipping containers piled on top of it.  How does anyone like that cruel visual of hurting a whale that way?  The orca of the current logo and the boxes is an attempt to nod at the existing Docker logo without going down their same dark path.  :)

**Comment by richardbmx** [comment]
perfect I will work on integrating containers to the idea and make a logo that expresses everything easily without hurting the whale. ;-)

**Comment by cjdesautels** [comment]
@frankfont, I never got that concept of containers from your crude effort. But it's a good idea if it can be done tastefully.

**Comment by richardbmx** [comment]
@frankfont @cjdesautels Greetings .. I present this modification of the logo that starts from the initial whale but now in a linear concept which gives seriousness simplicity and expresses the idea of ​​containers without hurting the whale, on the other hand you can see how it adapts very good to different backgrounds. I hope you like it if you want some change you should only request it, I will gladly do it.

![logo136mejorado](https://user-images.githubusercontent.com/35604837/59287785-601fc080-8c40-11e9-9a19-2f8f0b76b891.png)

**Comment by frankfont** [comment]
@richardbmx these are all terrific.  Logo has been updated, we added your name to the COLLABORATORS.md file.  Let us know if you would like us to include your email address there or anything like that.

**Comment by richardbmx** [comment]
@frankfont  I present here a folder of google drive with all the necessary files to use the logo within the folder you will find different variations of the logo so that you can use it in any way, additional to this there is a file that makes delivery of the copyright for that you can use the logo without problems.

[Google Drive](https://drive.google.com/open?id=1IuHnTW0RjG7B1Q2Osp6Xl_xV7JXy3fEb)

**Comment by frankfont** [comment]
@richardbmx that is terrific!  @cjdesautels has already updated the repo.
